### PR TITLE
build: github actions

### PR DESCRIPTION
**Pull request by kleo**
After build you can test then upload the artifact to releases.

### CODE REVIEW

**Review by nickdesaulniers — APPROVED** [review]
LGTM, though we'll have to be careful not to send this file upstream when sending the rest of the kernel changes.

**Comment by Wolfvak** [comment]
We can edit the wiki to reflect this.

**Comment by nickdesaulniers** [comment]
Yeah, let's create a separate section on the existing wiki pages for downloading the binaries.  Perhaps before the sections on how to download dependencies and build. I expect more users to download such binaries rather than build from source.

**Comment by Wolfvak** [comment]
A bit OT, but do you think making a buildroot + kernel build would time out the github CI? Just asking for future reference

**Comment by kleo** [comment]
@Wolfvak I can't say for sure but you can find the usage limits [here](https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration)

**Comment by Wolfvak** [comment]
awesome, thanks

**Pull request merged**
