### PR TITLE
reduce defconfig to a fragment

### PR DESCRIPTION
**Pull request by nickdesaulniers**
As part of the cpufreq driver work, I was looking at the
arch/arm/configs/nintendo3ds_defconfig thinking "that's way larger than
it should be."  Not that we're selecting more than we need (always a
possibility), but because the defconfigs under arch/{arch}/configs/ are
usually fragments.

To update a defconfig, you sould do:

1. Generate .config:
$ ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- make -j$(nproc) \
  nintendo3ds_defconfig

2. Update configs via menuconfig:
$ ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- make -j$(nproc) \
  menuconfig
<use y,n,m to select yes, no, module. / to search, Esc to get out, make
sure to save>

3. Generate defconfig diff:
$ ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- make -j$(nproc) \
  savedefconfig

4. Update nintendo3ds_defconfig:
$ cp defconfig arch/arm/configs/nintendo3ds_defconfig

Signed-off-by: Nick Desaulniers <nick.desaulniers@gmail.com>

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
you'll note, this fragment boils down changes we've made from the default state of configs. at 286 lines, it's more reasonable to understand what makes this configuration unique.  That's why it's a huge diff that only removes lines; there should be no functional change as a result of this change.  You can verify by diffing `.config` generated via `ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- make -j$(nproc) nintendo3ds_defconfig` before and after this change.

**Comment by nickdesaulniers** [comment]
I noticed that we're building:
CONFIG_EXT4_FS=y
CONFIG_F2FS_FS=y

can we turn these off until we're ready to mount a FS off disk?

**Comment by ParzivalWolfram** [comment]
Could lines that are unset be removed? There's still several there, if we're going for size...

**Comment by Wolfvak** [comment]
Ext4 and F2FS support are useful for mounting disk imagines as loopback (which were in turn mounted in a vfat SD)

**Review by Wolfvak — APPROVED** [review]

**Comment by nickdesaulniers** [comment]
> Could lines that are unset be removed?

Depends what the default state of a Kconfig is. If it's default on, having the line say it's disabled is important and shouldn't be removed.

Though menuconfig should always be used (as opposed to manually modifying the defconfig file or using scripts/config) such as not to mess up dependencies.

**Pull request merged**
