### PR TITLE
remove nr_cpus from bootargs in DTS

### PR DESCRIPTION
**Pull request by nickdesaulniers**
No other machines use these, I don't think they're necessary.

I still see a warning splat from DT either way.
https://github.com/linux-3ds/firm_linux_loader/pull/4/files#r606730803

Signed-off-by: Nick Desaulniers <nick.desaulniers@gmail.com>

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
actually, we might want to say nr_cpus=2 for CTR, that way we can have 1 kernel defconfig that says NR_CPUS=4, but the boot arg says "yeah but don't try to boot those 2 additional cores."  There's some slight overhead (double the amount of kernel memory for percpu variables), but for users is likely imperceptable and the benefit is we can have one kernel defconfig and hence image for either CTR/KTR models.

**Comment by nickdesaulniers** [comment]
can someone with CTR please test this diff (without this PR):
```diff
diff --git a/arch/arm/configs/nintendo3ds_defconfig b/arch/arm/configs/nintendo3ds_defconfig
index 8f71a65ac87a..e732e57d6921 100644
--- a/arch/arm/configs/nintendo3ds_defconfig
+++ b/arch/arm/configs/nintendo3ds_defconfig
@@ -338,7 +338,7 @@ CONFIG_VMSPLIT_3G=y
 # CONFIG_VMSPLIT_2G is not set
 # CONFIG_VMSPLIT_1G is not set
 CONFIG_PAGE_OFFSET=0xC0000000
-CONFIG_NR_CPUS=2
+CONFIG_NR_CPUS=4
 CONFIG_HOTPLUG_CPU=y
 CONFIG_ARCH_NR_GPIO=0
 CONFIG_HZ_FIXED=0
```
Does the machine still boot? Any new warnings in dmesg?

**Comment by Wolfvak** [comment]
just tried changing the variable in my own local repo and it still works fine

**Comment by nickdesaulniers** [comment]
> just tried changing the variable in my own local repo and it still works fine

Thanks, I've added that to this PR, PTAL.

**Comment by xerpi** [comment]
I think we have to set `CONFIG_NR_CPUS=4` and then on the old 3ds .dts set `nr_cpus=2`. (not fully sure)

**Comment by Wolfvak** [comment]
It worked fine for me, if no other cpu attempts to boot into the entrypoints for cpu2 and cpu3 then it times out and linux assumes there's only two. We need to add a cpu amount guard in the platsmp stuff though

**Review by Wolfvak — APPROVED** [review]

**Comment by nickdesaulniers** [comment]
> I think we have to set CONFIG_NR_CPUS=4 and then on the old 3ds .dts set nr_cpus=2. (not fully sure)

I think the pattern we want is:
```diff
diff --git a/arch/arm/mach-ctr/platsmp.c b/arch/arm/mach-ctr/platsmp.c
index fdd83011d7a1..3ea79080a955 100644
--- a/arch/arm/mach-ctr/platsmp.c
+++ b/arch/arm/mach-ctr/platsmp.c
@@ -49,15 +53,19 @@ static int ctr_smp_boot_secondary(unsigned int cpu,
        return 0;
 }
 
-static void ctr_smp_prepare_cpus(unsigned int max_cpus)
+static void __init ctr_smp_prepare_cpus(unsigned int max_cpus)
 {
        struct device_node *np;
        void __iomem *scu_base;
+       unsigned int i, ncores;
 
        np = of_find_compatible_node(NULL, NULL, "arm,arm11mp-scu");
        if (np) {
                scu_base = of_iomap(np, 0);
                scu_enable(scu_base);
+               ncores = scu_get_core_count(scu_base);
+               for (i = 0; i != ncores; ++i)
+                       set_cpu_possible(i, true);
                of_node_put(np);
        }
 }
```
Basically, you query the snoop control unit (SCU) at runtime to see how many cores there are, then update the mask of "possible cpus."

Let me add that, then if someone with CTR can test and check dmesg has no warnings would be good.

**Comment by Wolfvak** [comment]
latest commit works just fine on CTR

**Pull request merged**
